name: Jobs steps

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello There"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - run: echo "Byee"
  job-3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job 3"
  job-4:
    runs-on: ubuntu-latest
    needs:
      - job-2
      - job-3
    steps:
      - run: echo "job 3"
