name: Artifacts

on:
  workflow_dispatch:

jobs:
  artifact-producer:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Creation of artifacts" >> artifact.txt
      - uses: actions/upload-artifact@v4
        with:
          name: example-artifact
          path: artifact.txt
  artifact-consumer:
    runs-on: ubuntu-latest
    needs: artifact-producer
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: example-artifact
      - name: Cat artifact
        run: cat artifact.txt
