name: Git Hub Authentication

on:
  workflow_dispatch:

jobs:
  authenticate-github:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-south-1
          role-to-assume: arn:aws:iam::453194202742:role/GitHub-actions
