name: Passing Data

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest

    outputs:
      foo: ${{ steps.generate-foo.outputs.foo }}
    steps:
      - id: generate-foo
        run: |
          foo=bar
          echo "FOO=${foo}" >> "$GITHUB_ENV"
          echo "foo=${foo}" >> "$GITHUB_OUTPUT"
      - run: |
          echo $FOO
          echo "${{ steps.generate-foo.outputs.foo }}"
  job-2:
    runs-on: ubuntu-latest
    needs: job-1
    steps:
      - name: Something
        run: |
          echo $FOO
          echo "sdf ${{ needs.job-1.outputs.foo }}"
