name: Hello World

on:
  workflow_dispatch:

jobs:
  say-hello-world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!!"
  say-good-bye:
    runs-on: ubuntu-latest
    needs: say-hello-world
    steps:
      - run: echo "Good Bye!!"
